### ISSUE TITLE
grouping nomor dok di BBL

### ISSUE THREAD

**Issue by ifnrepo** [ifnrepo/ifnsystemweb#80]
Pada saat memilih bon permintaan (PB), nomor dokumen nya di grouping saja 
saat sesudah memilih nomor dokumen.. barang yang disimpan sesuai dengan nomor dokumen 
(tetap seperti sekarang)

![Image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/9a908d32-9a90-443f-bdfd-93a6295d76ae)

**Comment by ifnrepo** [comment]
Sudah oke, tapi kalau mencari data yang dengan keyword **_'001'_** yang muncul hanya 1 rekord paling atas saja.. padahal nomor_dok dengan angka **_001_** didalamnya ada banyak 
![image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/6a7addf2-59cb-4cbd-a45a-295f27a21db6)
Tolong disesuaikan lagi Vin

**Comment by kelvinkusmawan28** [comment]
siapp, sudah di tampilkan semua data berdasarkan keyword yang dicari dengan gruping data

**Comment by ifnrepo** [comment]
beres, ada beberapa perbaikan 
dibuat issue yang baru
