### ISSUE TITLE
(Modul BBL) PB masih bisa dipilih

### ISSUE THREAD

**Issue by ifnrepo** [ifnrepo/ifnsystemweb#81]
Bon Penerimaan (PB),
masih bisa dipilih padahal sudah jadi BBL 

![Image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/ac64f704-928a-4b3f-be1d-7c4f52fa6eda)

**Comment by kelvinkusmawan28** [comment]
sudah di realisasikan deangan penambahan kolom id_bbl di tb detail

**Comment by ifnrepo** [comment]
oke, done
