### ISSUE TITLE
(Modul BBL) filter bulan dan tahun

### ISSUE THREAD

**Issue by ifnrepo** [ifnrepo/ifnsystemweb#82]
Dibuatkan filter bulan dan tahun pada modul **BBL**
seperti halnya pada modul **PB**

![Image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/2d2cad83-79df-42ce-a481-40fefd03e48d)

**Comment by kelvinkusmawan28** [comment]
sudah di realisasikan

**Comment by ifnrepo** [comment]
done, oke
