### ISSUE TITLE
(Modul BBL) bon PB tujuan

### ISSUE THREAD

**Issue by ifnrepo** [ifnrepo/ifnsystemweb#83]
Bon PB yang bisa dipilih harus yang ditujukan ke departemen _**Asal Pembuatan BBL**_

![Image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/466a29b8-e7aa-4887-b39e-da006ec2ad40)

**Comment by kelvinkusmawan28** [comment]
sudah di realisasikan

**Comment by ifnrepo** [comment]
Select input yang ini dihilangkan saja Vin, 
soalnya di depan sudah terlihat Departemen yang membuat BBL
![image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/3da48260-8e50-4ab9-91c2-0d386cf2e363)
![image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/304212f1-5239-4d55-b76d-57a1df7a9e6c)

**Comment by kelvinkusmawan28** [comment]
siapp ,sudah di realisasikan kembali mohon di cek

**Comment by ifnrepo** [comment]
beres Vin,
