### ISSUE TITLE
Fix Issue Tanggal dan Bon PB

### ISSUE THREAD

**Issue by ifnrepo** [ifnrepo/ifnsystemweb#93]
1. Tanggal dan Catatan belum bisa dirubah

![image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/9804f580-600c-493f-a781-c3f98ac9a6bf)

Ada sedikit perubahan pada form BBL 
Tombol get/cari permintaan dan penambahan kolom pada modal pencarian data 

2. Pada saat BBL **dihapus,**, Bon PB  tidak bisa dipilih kembali (harusnya bisa karena belum close)
3. BBL masih kosong tapi sudah bisa disimpan

**Comment by kelvinkusmawan28** [comment]
sudah di realisasikan ,mohon di cek

#noted filter pencarian tidak menggunakan nomor dokumen,,tapi nama barang

**Comment by ifnrepo** [comment]
oke vin, done
