### ISSUE TITLE
Pembuatan Form PONET

### ISSUE THREAD

**Issue by ifnrepo** [ifnrepo/ifnsystemweb#96]
- Buatkan menu baru dengan nama PONET 
- Buatkan hak akses (ceklis) di Menu User Manajemen untuk menu INVENTORY & PONET pada tab Other (Tab Baru) letakan diantara Tab Transaksi dan Tab User Manajemen

![image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/17d253fd-1b79-4f21-8569-d04e4077b797)

- Pembuatan Form Ponet sesuai/mirip dengan PONET (desktop) yang ada di Server/Simpro

![image](https://github.com/ifnrepo/ifnsystemweb/assets/148191319/ab44591c-bdf3-480c-9d99-d7cc6717cdff)

**Comment by kelvinkusmawan28** [comment]
pembuatan menu baru  dengan nama PONET sudah di realisasikan , klo untuk form ponet masih menggunakan yg sederhana

**Comment by ifnrepo** [comment]
Pembuatan form untuk PONET dilanjutkan, 
punten UI-nya diperhatikan vin

**Comment by Atepasep** [comment]
Pembuatan UI terus di perbaiki dengan supervisi dari Pak Jamhur
